### PR TITLE
added new file called hahaha.docx

### PR DESCRIPTION
**Pull request by MatthewSwartz**
file to show I did all the introduction steps.

### CODE REVIEW

**Comment by bcohen116** [comment]
Great. Any trouble with the steps? We look forward to working with you.

**Comment by MatthewSwartz** [comment]
Hello,
Could I get the name of the other person who is designing the UI for the
website? Also, where should I write out the code and where do I begin to
start with the coding?
Thank you,
Matthew

**Comment by bcohen116** [comment]
Max Fritzhand should also be working on the UI. As far as where to code. You can code it from anywhere as long as you save the file in your GitHub folder. Some common HTML IDE's are: Netbeans (with the plugin installed), Dreamweaver, or even Notepad works, though notepad doesn't have code correction.

Give us a few days for our graphical people to mark up a visual representation. Then you can start to code that into a real webpage. If you want to try out some coding now, you can look up the bootstrap template examples (http://getbootstrap.com/getting-started/#examples) and play around with some of the buttons and other even some other features you may not have much experience with. All of those example templates are forked to our GitHub and can be found under https://github.com/AviatorFlightPlan/bootstrap/tree/master/docs/examples. You can download all of them to your computer the same way as you did the AviatorFlightPlan to be able to edit them.

Good Luck,
Ben

**Comment by MaxFritzhand** [comment]
How should I start doing the UI? I don't really know what to base it off...have any drawings or anything?

**Comment by bcohen116** [comment]
I'm sorry, I answered your question in that post, but it looks like it didn't send correctly so you only got half of the message. Here's what I said: "Give us a few days for our graphical people to mark up a visual representation. Then you can start to code that into a real webpage. If you want to try out some coding now, you can look up the bootstrap template examples (http://getbootstrap.com/getting-started/#examples) and play around with some of the buttons and other even some other features you may not have much experience with. All of those example templates are forked to our GitHub and can be found under https://github.com/AviatorFlightPlan/bootstrap/tree/master/docs/examples. You can download all of them to your computer the same way as you did the AviatorFlightPlan to be able to edit them."

Good Luck,
Ben

**Comment by bcohen116** [comment]
I just added some pictures to the GitHub you can use to fiddle around with. Feel free to make some prototypes over break and send in some pictures.

**Comment by MatthewSwartz** [comment]
So that we can all begin from the same point, will you guys be able to meet
after school on Monday for an hour? I need some help getting started.

Matthew

**Comment by bcohen116** [comment]
I'll contact Griffin and let you know. He doesn't check his email often it seems so I might not be able to get back to you until 5th bell.

-Ben

**Comment by MatthewSwartz** [comment]
Alright, that's fine. I will be staying after school anyways.
Thank you
Matthew

**Comment by bcohen116** [comment]
I just uploaded a sample UI that I think contains everything that we are looking for. It even has a working dropdown, You can take a look at it for inspiration. You will need to download the UI Prototypes folder to your pc, then find the .html file and open that to view it.

**Pull request closed without merging**
